version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run build
  artifacts:
    files:
      - "**/*"
    base-directory: /dist # Directory with output files (e.g., React app)
