version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - export VITE_S3_BUCKET=$VITE_S3_BUCKET
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://my-frontend-bucket-finalproject  --delete
      - aws cloudfront create-invalidation --distribution-id EWT4OLTFNB0GM --paths "/*"
